// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.MultiActivate = (function() {
    var NAME, SEQUENCE, _current_ma_version, _dbg_mode;

    _dbg_mode = null;

    _current_ma_version = null;

    SEQUENCE = null;

    NAME = null;

    function MultiActivate() {
      _dbg_mode = Constants.is_debug_mode();
      _current_ma_version = Constants.get_current_activate_pattern_version();
      SEQUENCE = ['TAB_ACTIVATED', 'TAB_ACTIVATED', 'TAB_ACTIVATED', 'TAB_ACTIVATED'];
      NAME = "MULTI_ACTIVATE_" + _current_ma_version;
    }

    MultiActivate.prototype.sequence = function() {
      return SEQUENCE;
    };

    MultiActivate.prototype.name = function() {
      return NAME;
    };

    return MultiActivate;

  })();

}).call(this);
