// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var API_URL, BATCH_SIZE, DEBUG_MODE, USER_ID, connection, identifier, usage_logger;

  API_URL = 'http://localhost:9292';

  DEBUG_MODE = true;

  BATCH_SIZE = 50;

  identifier = new Identifier;

  USER_ID = identifier.get_or_generate_id();

  console.log("User id: " + USER_ID);

  connection = new Connection(API_URL, DEBUG_MODE);

  usage_logger = new UsageLogger(connection, BATCH_SIZE, USER_ID, DEBUG_MODE);

  usage_logger.start();

}).call(this);
