// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var API_URL, BATCH_SIZE, DEBUG_MODE, connection, user;

  API_URL = 'http://tabber.fiit.stuba.sk';

  DEBUG_MODE = false;

  BATCH_SIZE = 50;

  connection = new Connection(API_URL, DEBUG_MODE);

  user = new User(connection);

  user.in_context(function(user_id, session_id) {
    var usage_logger;
    usage_logger = new UsageLogger(connection, BATCH_SIZE, user_id, session_id, DEBUG_MODE);
    return usage_logger.start();
  });

}).call(this);
