// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Constants = (function() {
    var DEBUG_MODE;

    function Constants() {}

    DEBUG_MODE = false;

    Constants.is_debug_mode = function() {
      return DEBUG_MODE;
    };

    Constants.get_api_url = function() {
      if (DEBUG_MODE) {
        return 'http://localhost:9292';
      } else {
        return 'http://tabber.fiit.stuba.sk:9292';
      }
    };

    Constants.get_batch_size = function() {
      if (DEBUG_MODE) {
        return 5;
      } else {
        return 50;
      }
    };

    return Constants;

  })();

}).call(this);
