// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var load_options, reset_options, save_option;

  reset_options = function() {
    $('#user-level-select').val('beginner');
    return $('#rec-mode-select').val('semi-interactive');
  };

  load_options = function() {
    return chrome.storage.sync.get(['user_level', 'rec_mode'], function(result) {
      if (result.user_level && result.rec_mode) {
        $('#user-level-select').val(result.user_level);
        return $('#rec-mode-select').val(result.rec_mode);
      } else {
        return reset_options();
      }
    });
  };

  save_option = function() {
    var recMode, userLevel;
    userLevel = $('#user-level-select').val();
    recMode = $('#rec-mode-select').val();
    return chrome.storage.sync.set({
      'user_level': userLevel,
      'rec_mode': recMode
    }, function() {
      return swal('Success!', 'Your settings has been saved!', 'success');
    });
  };

  $('#save-settings').click(function() {
    return save_option();
  });

  $('#reset-settings').click(function() {
    return reset_options();
  });

  $(document).ready(function() {
    return load_options();
  });

}).call(this);
