// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Connection = (function() {
    var api_url, debug_mode, get_collection, get_member, post_collection, post_member;

    function Connection() {}

    debug_mode = Constants.is_debug_mode();

    api_url = Constants.get_api_url();

    Connection.prototype.get_user = function(id, callback) {
      return get_member(api_url, 'users', id, callback);
    };

    Connection.prototype.get_user_bstats = function(id, callback) {
      return get_member(api_url, 'stats/browsing', id, callback);
    };

    Connection.prototype.create_user = function(data) {
      return post_member(api_url, data, 'users');
    };

    Connection.prototype.post_usage_logs = function(data) {
      return post_collection(api_url, data, 'logs/usage');
    };

    get_member = function(url, resource, id, callback) {
      return $.ajax("" + url + "/" + resource + "/" + id, {
        type: 'GET',
        dataType: 'json',
        error: function(jqXHR, textStatus, errorThrown) {
          return callback(null);
        },
        success: function(data, textStatus, jqXHR) {
          return callback(data);
        }
      });
    };

    get_collection = function(url, resource) {
      return $.ajax("" + url + "/" + resource, {
        type: 'GET',
        dataType: 'json',
        error: function(jqXHR, textStatus, errorThrown) {
          if (debug_mode) {
            return console.log("Error: " + textStatus);
          }
        },
        success: function(data, textStatus, jqXHR) {
          var event, _i, _len, _results;
          if (debug_mode) {
            _results = [];
            for (_i = 0, _len = data.length; _i < _len; _i++) {
              event = data[_i];
              _results.push(console.log("" + event['name']));
            }
            return _results;
          }
        }
      });
    };

    post_member = function(url, data, resource) {
      return $.ajax("" + url + "/" + resource, {
        type: 'POST',
        dataType: 'json',
        data: {
          user: data
        },
        success: function(data, textStatus, jqXHR) {
          if (debug_mode) {
            return console.log("Status: " + textStatus);
          }
        }
      });
    };

    post_collection = function(url, data, resource) {
      return $.ajax("" + url + "/" + resource, {
        type: 'POST',
        dataType: 'json',
        data: {
          data: data
        },
        success: function(data, textStatus, jqXHR) {
          if (debug_mode) {
            console.log("Status: " + textStatus);
            return console.log(data);
          }
        }
      });
    };

    return Connection;

  })();

}).call(this);
