// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Indentifier = (function() {
    var generate_uuid;

    function Indentifier() {}

    Indentifier.prototype.load_or_generate_id = function() {
      var uid;
      uid = chrome.storage.sync.get(['user_id'], function(result) {
        return result.user_id;
      });
      if (uid) {
        return uid;
      } else {
        uid = generate_uuid();
        chrome.storage.sync.set({
          'user_id': uid
        });
        return uid;
      }
    };

    generate_uuid = function() {
      return console.log("Generating uuid");
    };

    return Indentifier;

  })();

}).call(this);
