// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Identifier = (function() {
    function Identifier() {}

    Identifier.prototype.get_or_generate_id = function() {
      var id;
      id = chrome.storage.sync.get(['user_id'], function(result) {
        return result.user_id;
      });
      if (id) {
        return id;
      } else {
        id = UUID.create(4);
        chrome.storage.sync.set({
          'user_id': id
        });
        return id;
      }
    };

    return Identifier;

  })();

}).call(this);
