// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Logger = (function() {
    var get;

    function Logger(url) {
      this.url = url;
    }

    Logger.prototype.log = function(message) {
      return console.log("Logging: " + message + " to server: " + this.url);
    };

    Logger.prototype.getUser = function(id) {
      return get(this.url, 'users', id);
    };

    get = function(url, resource, id) {
      return $.ajax("" + url + "/" + resource + "/" + id, {
        type: 'GET',
        dataType: 'json',
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("Error: " + textStatus);
        },
        success: function(data, textStatus, jqXHR) {
          return console.log("User id: " + data['id'] + " experience: " + data['experience'] + " rec_mode: " + data['rec_mode']);
        }
      });
    };

    return Logger;

  })();

}).call(this);
