// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Notifier = (function() {
    function Notifier() {}

    Notifier.prototype.notify = function() {
      return console.log('Notifying...');
    };

    return Notifier;

  })();

}).call(this);
