// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Notifier = (function() {
    function Notifier() {}

    Notifier.prototype.notify = function(message) {
      return console.log("Notifiyng: " + message);
    };

    return Notifier;

  })();

}).call(this);
