// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Recognizer = (function() {
    function Recognizer() {}

    Recognizer.prototype.recognize = function() {
      return console.log('Recognizer started...');
    };

    return Recognizer;

  })();

}).call(this);
