// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Recognizer = (function() {
    function Recognizer() {}

    Recognizer.prototype.recognize = function() {
      return console.log('zavolal z recognizera');
    };

    return Recognizer;

  })();

  this.BasicRecognizer = (function() {
    function BasicRecognizer() {}

    BasicRecognizer.prototype.basic = function() {
      return console.log('zavolal basic recognizera');
    };

    return BasicRecognizer;

  })();

}).call(this);
