// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.Recognizer = (function() {
    var current_state_is_pattern, get_current_ts, has_suffix, not_inside_timeout, process_event, tab_activated, tab_attached, tab_created, tab_detached, tab_moved, tab_removed, tab_updated, _activate_pattern, _current_sequence, _dbg_mode, _last_event_time, _last_pattern_time, _max_gap, _notifier, _patterns, _rec_timeout;

    _dbg_mode = Constants.is_debug_mode();

    _rec_timeout = Constants.get_rec_timeout();

    _notifier = null;

    function Recognizer(user_id, session_id) {
      _notifier = new Notifier(user_id);
    }

    Recognizer.prototype.start = function() {
      if (_dbg_mode) {
        console.log("Pattern recognizer has started!");
      }
      chrome.tabs.onCreated.addListener(tab_created);
      chrome.tabs.onRemoved.addListener(tab_removed);
      chrome.tabs.onActivated.addListener(tab_activated);
      chrome.tabs.onMoved.addListener(tab_moved);
      chrome.tabs.onAttached.addListener(tab_attached);
      chrome.tabs.onDetached.addListener(tab_detached);
      return chrome.tabs.onUpdated.addListener(tab_updated);
    };

    _last_event_time = null;

    _max_gap = Constants.get_max_gap();

    _current_sequence = [];

    _last_pattern_time = null;

    _activate_pattern = {
      sequence: ['TAB_ACTIVATED', 'TAB_ACTIVATED', 'TAB_ACTIVATED', 'TAB_ACTIVATED'],
      name: 'MULTI_ACTIVATE_V2'
    };

    _patterns = [_activate_pattern];

    tab_created = function(tab) {
      return process_event('TAB_CREATED', get_current_ts());
    };

    tab_removed = function(tab_id, remove_info) {
      return process_event('TAB_REMOVED', get_current_ts());
    };

    tab_activated = function(active_info) {
      return process_event('TAB_ACTIVATED', get_current_ts());
    };

    tab_moved = function(tab_id, move_info) {
      return process_event('TAB_MOVED', get_current_ts());
    };

    tab_attached = function(tab_id, attach_info) {
      return process_event('TAB_ATTACHED', get_current_ts());
    };

    tab_detached = function(tab_id, detach_info) {
      return process_event('TAB_DETACHED', get_current_ts());
    };

    tab_updated = function(tab_id, change_info, tab) {
      if (change_info.status === 'complete') {
        return process_event('TAB_UPDATED', get_current_ts());
      }
    };

    process_event = function(event_name, time_occured) {
      var pattern;
      if (_last_event_time === null || (time_occured - _last_event_time) < _max_gap) {
        _current_sequence.push(event_name);
        if ((pattern = current_state_is_pattern(_current_sequence)) && not_inside_timeout(get_current_ts())) {
          _notifier.show_pattern(pattern);
          _last_pattern_time = get_current_ts();
          _current_sequence = [];
        }
      } else {
        _current_sequence = [];
      }
      return _last_event_time = time_occured;
    };

    current_state_is_pattern = function(sequence) {
      var pattern, _i, _len;
      if (_dbg_mode) {
        console.log("Current sequence: " + sequence);
      }
      for (_i = 0, _len = _patterns.length; _i < _len; _i++) {
        pattern = _patterns[_i];
        if (has_suffix(sequence.toString(), pattern.sequence.toString())) {
          return pattern.name;
        }
      }
      return false;
    };

    not_inside_timeout = function(current_time) {
      if (_last_pattern_time === null || current_time - _last_pattern_time > _rec_timeout) {
        return true;
      } else {
        return false;
      }
    };

    get_current_ts = function() {
      return new Date().getTime();
    };

    has_suffix = function(str, suffix) {
      return str.indexOf(suffix, str.length - suffix.length) !== -1;
    };

    return Recognizer;

  })();

}).call(this);
