// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.StorageManager = (function() {
    var generate_uuid;

    function StorageManager() {}

    StorageManager.prototype.load = function() {
      return console.log("Loading from storage");
    };

    StorageManager.prototype.save = function() {
      return console.log("Saving to storage");
    };

    StorageManager.prototype.get_user_id = function() {
      console.log("Getting user id");
      return 123456;
    };

    generate_uuid = function() {
      return console.log("Generating uuid");
    };

    return StorageManager;

  })();

}).call(this);
