// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.UsageLogger = (function() {
    var cache, cache_usage_log, post_usage_logs, tab_activated, tab_created, tab_removed, _conn;

    _conn = null;

    function UsageLogger(connection) {
      this.connection = connection;
      _conn = this.connection;
    }

    UsageLogger.prototype.start = function() {
      console.log("Usage logger has started!");
      chrome.tabs.onCreated.addListener(tab_created);
      chrome.tabs.onRemoved.addListener(tab_removed);
      return chrome.tabs.onActivated.addListener(tab_activated);
    };

    cache = [];

    cache_usage_log = function(log) {
      console.log("Caching usage log: Tab id: " + log.tab_id + ", Event: " + log.event + ", Time: " + log.timestamp);
      cache.push(log);
      console.log("Cache size: " + cache.length);
      if (cache.length > 9) {
        return post_usage_logs();
      }
    };

    post_usage_logs = function() {
      console.log("!!! Posting usage logs.");
      _conn.post_usage_logs(cache);
      return cache.length = 0;
    };

    tab_created = function(tab) {
      return cache_usage_log({
        tab_id: tab.id,
        event: 'TAB_CREATE',
        timestamp: new Date().getTime()
      });
    };

    tab_removed = function(tab_id, remove_info) {
      return cache_usage_log({
        tab_id: tab_id,
        event: 'TAB_REMOVE',
        timestamp: new Date().getTime()
      });
    };

    tab_activated = function(active_info) {
      return cache_usage_log({
        tab_id: active_info.tabId,
        event: 'TAB_ACTIVATE',
        timestamp: new Date().getTime()
      });
    };

    return UsageLogger;

  })();

}).call(this);
