// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  this.UUID = (function() {
    var generate_uuid;

    function UUID() {}

    UUID.prototype.load_or_generate = function() {
      console.log("Getting user id");
      return 123456;
    };

    generate_uuid = function() {
      return console.log("Generating uuid");
    };

    return UUID;

  })();

}).call(this);
